title: Fun with Functors
description: Thoughts on programming, Scala, Spark, and functional ideas
url: "https://lukemcphee.github.io"
baseurl: "/funwithfunctors"

markdown: kramdown
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
