title: Fun with Functors
description: Welcome
url: "https://lukemcphee.github.io"
baseurl: "/funwithfunctors"

markdown: kramdown
remote_theme: pages-themes/minimal@v0.2.0

plugins:
  - jekyll-remote-theme
